### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-react-dom#7]
`bower.json` implies its MIT, but it might be good to make it explicit.

**Comment by ethul** [comment]
I'd be happy to add a license file. Should I make it similar to the one in `purescript-react`?

**Comment by paf31** [comment]
Looks like `bower.json` specified MIT from the first commit, so I think that's fine, yeah. Thanks!

**Comment by ethul** [comment]
Great! Just added the file. Thanks!
